languageCode = "en"
languageName = "English"
weight = 1
title = "Val's blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 Jan, 2006"
   logo = "img/big-cat.webp"
   secondaryLogo = "img/lain-bear-icon.jpg"
    description = "My awesome website"
#   copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Valentin B"
   image = "img/lain-bear-icon.jpg"
   headline = "Welcome to my blog"
   bio = "Focusing on mastering penetration testing and digital forensics"
   links = [
      { email = "mailto:valentinbergamotto@gmail.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://www.facebook.com" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
      { github = "https://github.com/LiLTrash1" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://www.instagram.com//" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://www.pinterest.co.uk/LiLVal_16/" },
#     { reddit = "https://www.reddit.com/user/LiLTrash_/" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/" },
#     { soundcloud = "https://soundcloud.com/" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/76561198385909481/" },
#     { telegram = "https://t.me" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://www.twitch.tv/" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/" },
#     { youtube = "https://www.youtube.com/channel/" },
#     { ko-fi = "https://ko-fi.com/" },
   ]
