colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }

[header]
layout = "basic"
languageSwitcher = true

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = false
cardViewScreenWidth = true
layoutBackgroundBlur = true
disableHeroImageFilter = false
homepageImage = "img/SANY0530.JPG"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = true
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = true
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 6
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = true
showWordCount = true
showZenMode = false

[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
